name: AbyssEconomy
version: '1.0.5'
main: net.abyssdev.abysseconomy.AbyssEconomy
api-version: 1.13
depend:
    - AbyssLib
softdepend:
    - PlaceholderAPI
authors:
    - Relocation
website: https://abyssdev.net
